export const PROPS = {
    // Allowed read-only DOM properties for safe inspection of element state (no setters / no mutation)
    whitelist: [
        "baseURI",
        "childElementCount",
        "clientHeight",
        "clientLeft",
        "clientTop",
        "clientWidth",
        "currentSrc",
        "duration",
        "ended",
        "isConnected",
        "localName",
        "naturalHeight",
        "naturalWidth",
        "namespaceURI",
        "networkState",
        "nodeName",
        "nodeType",
        "offsetHeight",
        "offsetLeft",
        "offsetTop",
        "offsetWidth",
        "paused",
        "readyState",
        "scrollHeight",
        "scrollWidth",
        "seeking",
        "tagName",
        "validationMessage",
        "videoHeight",
        "videoWidth",
        "willValidate",
        "x",
        "y",
    ],
};
